name:                advent
version:             0.1.0.0
github:              "saxj/advent"
license:             BSD3
author:              "Saxon Jensen"
maintainer:          "saxon.jensen@gmail.com"
copyright:           "2020 Saxon Jensen"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/agentultra/advent#readme>

dependencies:
- base-noprelude >= 4.7 && < 5

default-extensions:
- OverloadedStrings
- TypeApplications

library:
  source-dirs: src
  dependencies:
  - relude
  - text
  - directory
  - scanf
  - split
  - containers
  - regex-tdfa
  - binary

executables:
  advent2020:
    main:                Main.hs
    source-dirs:         app/Y2020/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Y2020.Main
    dependencies:
    - advent

tests:
  advent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent
    - hspec
